### ISSUE TITLE
Could you please add Gradle wrapper to simplify project build?

### ISSUE THREAD

**Issue by vbauer** [shiraji/new-instance-inspection#8]

**Comment by shiraji** [comment]
I tried to work on this plugin using [gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin) in last year, didn't success. Maybe it's time to try it again, since a lot of my plugin uses the library. Thanks for bringing this.

**Comment by shiraji** [comment]
Implemented it. Thanks for reporting this.

I don't release this version since there is no changed for users.

**Comment by vbauer** [comment]
Thank you very much!
